### ISSUE TITLE
CompileSol fails when importing from contract from parent directory

### ISSUE THREAD

**Issue by brianlai98** [ConsenSys/solc-typed-ast#137] opened 2022-07-28 02:44 UTC
## Environment
Node: v16.14.2
solc-typed-ast 10.1.4

## Scenario
`compileSol` fails when importing a contract from parent directory.

## Reproducing the error
1. write `index.ts`
```
import { compileSol } from 'solc-typed-ast';

const contractPaths = [
    './contracts/foo.sol',
    './contracts/dir/bar.sol',
]
// @ts-ignore
compileSol(contractPaths, "auto", [])
```
2.  `write contract/foo.sol`
```
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.13;

contract Foo {
}
```
3. write `contract/dir/bar.sol`
```
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.13;
import '../foo.sol';

contract Bar is Foo {
}
```

5. run `npx ts-node index.ts`
## Expected behavior
Should compile successfully.

## Current behavior
`CompileInferenceError: Couldn't find contracts/foo.sol`

**Comment by blitz-1306** [comment] 2022-08-01 05:22
Hello there @brianlai98 and thanks for the input.

I managed to make your case working by removing `./` common prefix from paths. Try this:
```typescript
import { ASTReader, compileSol } from 'solc-typed-ast';

const contractPaths = [
    'contracts/foo.sol',
    'contracts/dir/bar.sol',
];

// @ts-ignore
compileSol(contractPaths, "auto", []).then((result) => {
    const reader = new ASTReader();

    const units = reader.read(result.data);

    units.forEach((unit) => console.log(unit.print()));
});
```
You can also provide `basePath` to avoid an issue:
```typescript
import { ASTReader, compileSol } from 'solc-typed-ast';

const contractPaths = [
    'foo.sol',
    'dir/bar.sol',
];

// @ts-ignore
compileSol(contractPaths, "auto", { basePath: "./contracts" }).then((result) => {
    const reader = new ASTReader();

    const units = reader.read(result.data);

    units.forEach((unit) => console.log(unit.print()));
});
```

The mentioned approaches above are a _workarounds_.

The root of the issue is in `findAllFiles()` as `./contracts/foo.sol` and `contracts/foo.sol` are considered different and `./contracts/foo.sol` is not found. The input file stored as `./contracts/foo.sol`, but when resolving `contracts/dir/bar.sol` the resolver tries to find `contracts/foo.sol` instead and misses.

**Comment by blitz-1306** [comment] 2022-08-03 06:00
The issue is caused by not properly auto-detecting `basePath` here: https://github.com/ConsenSys/solc-typed-ast/blob/a3ebbf779fefe9db50b4c8394750290195942ec4/src/compile/utils.ts#L299-L304

Basically, it _resets_ `basePath` each time for each new file. This handles some cases, but ignores the others (like mentioned in the original post). I do not yet see way to properly fix this, except provide `basePath` externally., except try not to detect it and ask user to provide base paths. However, this would break BC in dependent packages.

**Comment by brianlai98** [comment] 2022-08-04 20:50
Hi @blitz-1306 thanks for the detailed explanation. The workaround you described works perfectly for me.

**Comment by blitz-1306** [comment] 2023-06-12 06:02
I'm closing this issue due to it seems to be solved via use of `basePath` compile option. Other solutions does not seem to be reliable.

**Closed by blitz-1306** 2023-06-12 06:02 UTC
Labels: bug

**Comment by maanas2605** [comment] 2023-09-16 05:07
The same issue exists when absolute file paths are given too and can be avoided if instead basePath configuration is used.
When resolving the file path in the resolveSourceUnitName() function, the entire path of the file is joined with the basePath by resolvers https://github.com/Consensys/solc-typed-ast/blob/8b30533342b36426f6b75b767d87e363056bfda1/src/compile/import_resolver.ts#L33 
For absolute paths, can't this resolving step be avoided?
